---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
      skip: true

- name: Install gpg-agent on new distros
  apt:
    name: gpg-agent
  when:
    - ansible_distribution == 'Debian' and ansible_distribution_major_version is version('11','>=')
    - syslog_repo_key is defined

- name: Install GPG-KEY with get_url
  ansible.builtin.get_url:
    url: "{{ syslog_repo_key }}"
    dest: /etc/apt/keyrings/syslog-ng-ose.gpg
    mode: '0644'
  when:
    - ansible_os_family == 'Debian'
    - syslog_repo_key is defined

- name: Ensure syslog-ng repo is present Debian
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/syslog-ng-ose.gpg] {{ syslog_repository }} stable {{ syslog_os_version }}"
  when:
    - ansible_os_family == 'Debian'
    - syslog_repository is defined
    - syslog_os_version is defined

- name: Import GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ syslog_repo_key }}"
  when:
    - ansible_os_family == 'RedHat'
    - syslog_repo_key is defined

- name: Ensure syslog-ng repo is present RHEL
  ansible.builtin.yum_repository:
    name: syslog-ng
    description: syslog-ng repo
    baseurl: "{{ syslog_repository }}{{ syslogng_os_version }}"
  when:
    - ansible_os_family == 'RedHat'
    - syslog_repository is defined
    - syslog_os_version is defined

- name: install requirements
  ansible.builtin.package:
    name: "{{ syslog_dependencies }}"
    state: present
  when:
    - syslog_dependencies | default([]) | count > 0

- name: merge syslog configuration between defaults and custom
  ansible.builtin.set_fact:
    syslog_options: "{{ syslog_defaults_options | combine(syslog_options, recursive=True) }}"
    syslog_sources: "{{ syslog_defaults_sources | combine(syslog_sources, recursive=True) }}"
    syslog_message_templates: "{{ syslog_defaults_message_templates | combine(syslog_message_templates, recursive=True) }}"
    syslog_logs: "{{ syslog_defaults_logs | combine(syslog_logs, recursive=True) }}"

- name: defined log directories
  ansible.builtin.set_fact:
    syslog_server_log_destinations: "{{ syslog_logs | log_directories('/var/log') }}"
